name: 🚀 Release Planning
description: Plan a new release with proper versioning
title: "[Release] v"
labels: ["release", "planning"]
body:
  - type: markdown
    attributes:
      value: |
        ## Release Planning
        
        Use this template to plan a new release. The release will be automated via semantic-release when commits are pushed.

  - type: dropdown
    id: release-type
    attributes:
      label: Release Type
      description: What type of release is this?
      options:
        - Patch (Bug fixes, 1.0.0 → 1.0.1)
        - Minor (New features, 1.0.0 → 1.1.0)
        - Major (Breaking changes, 1.0.0 → 2.0.0)
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: Planned Changes
      description: List the commits/changes that will be included
      placeholder: |
        - fix: resolve notification crash
        - feat: add dark mode toggle
        - fix(auth): handle token expiration
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How will this be deployed?
      options:
        - EAS Update (OTA) - Users auto-update
        - EAS Build (APK) - Users must reinstall
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-Release Checklist
      options:
        - label: All commits follow Conventional Commits format
          required: true
        - label: BREAKING CHANGE footer added if major release
          required: false
        - label: Tested locally on Android device
          required: true
        - label: No uncommitted changes
          required: true
        - label: EXPO_TOKEN secret configured in GitHub
          required: true
        - label: Ready to push to main branch
          required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any other information about this release
      placeholder: |
        Migration steps for users (if breaking change)
        Known issues
        Special testing requirements
