name: Production Build and Update
description: Build production APK with ProGuard optimization and publish OTA update

on:
  workflow_dispatch:
    inputs:
      skip_build:
        type: boolean
        description: Skip APK build (OTA update only)
        default: false

jobs:
  build:
    name: Build Production APK
    if: ${{ !inputs.skip_build }}
    steps:
      - eas/build:
          platform: android
          profile: production
          message: "Production build v${{ eas.project.version }}"

  update:
    name: Publish OTA Update
    needs: [build]
    if: always() # Run even if build is skipped
    steps:
      - eas/update:
          branch: production
          message: "OTA update - ${{ github.event.head_commit.message }}"
